/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaibaMaisRouteImport } from './routes/saiba-mais'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as EncerramentoRouteImport } from './routes/encerramento'
import { Route as AnamneseRouteImport } from './routes/anamnese'
import { Route as AmbienteRouteImport } from './routes/ambiente'
import { Route as IndexRouteImport } from './routes/index'

const SaibaMaisRoute = SaibaMaisRouteImport.update({
  id: '/saiba-mais',
  path: '/saiba-mais',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const EncerramentoRoute = EncerramentoRouteImport.update({
  id: '/encerramento',
  path: '/encerramento',
  getParentRoute: () => rootRouteImport,
} as any)
const AnamneseRoute = AnamneseRouteImport.update({
  id: '/anamnese',
  path: '/anamnese',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbienteRoute = AmbienteRouteImport.update({
  id: '/ambiente',
  path: '/ambiente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ambiente': typeof AmbienteRoute
  '/anamnese': typeof AnamneseRoute
  '/encerramento': typeof EncerramentoRoute
  '/pacientes': typeof PacientesRoute
  '/painel': typeof PainelRoute
  '/saiba-mais': typeof SaibaMaisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ambiente': typeof AmbienteRoute
  '/anamnese': typeof AnamneseRoute
  '/encerramento': typeof EncerramentoRoute
  '/pacientes': typeof PacientesRoute
  '/painel': typeof PainelRoute
  '/saiba-mais': typeof SaibaMaisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ambiente': typeof AmbienteRoute
  '/anamnese': typeof AnamneseRoute
  '/encerramento': typeof EncerramentoRoute
  '/pacientes': typeof PacientesRoute
  '/painel': typeof PainelRoute
  '/saiba-mais': typeof SaibaMaisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ambiente'
    | '/anamnese'
    | '/encerramento'
    | '/pacientes'
    | '/painel'
    | '/saiba-mais'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ambiente'
    | '/anamnese'
    | '/encerramento'
    | '/pacientes'
    | '/painel'
    | '/saiba-mais'
  id:
    | '__root__'
    | '/'
    | '/ambiente'
    | '/anamnese'
    | '/encerramento'
    | '/pacientes'
    | '/painel'
    | '/saiba-mais'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AmbienteRoute: typeof AmbienteRoute
  AnamneseRoute: typeof AnamneseRoute
  EncerramentoRoute: typeof EncerramentoRoute
  PacientesRoute: typeof PacientesRoute
  PainelRoute: typeof PainelRoute
  SaibaMaisRoute: typeof SaibaMaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saiba-mais': {
      id: '/saiba-mais'
      path: '/saiba-mais'
      fullPath: '/saiba-mais'
      preLoaderRoute: typeof SaibaMaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encerramento': {
      id: '/encerramento'
      path: '/encerramento'
      fullPath: '/encerramento'
      preLoaderRoute: typeof EncerramentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anamnese': {
      id: '/anamnese'
      path: '/anamnese'
      fullPath: '/anamnese'
      preLoaderRoute: typeof AnamneseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambiente': {
      id: '/ambiente'
      path: '/ambiente'
      fullPath: '/ambiente'
      preLoaderRoute: typeof AmbienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AmbienteRoute: AmbienteRoute,
  AnamneseRoute: AnamneseRoute,
  EncerramentoRoute: EncerramentoRoute,
  PacientesRoute: PacientesRoute,
  PainelRoute: PainelRoute,
  SaibaMaisRoute: SaibaMaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
